NationalLibraryOfNorway/ngx-mime

.gitignore

- Removed autogenerated css file from scss
- Added css to .gitignore

fix(viewer): removed autogenerated css

---

.travis.yml
package.json

Added access public to npm publish

fix(build): added access public to npm publish

---

README.md
guides/getting-started.md

- Installation
- Getting started
- Project status

docs(*): updated and new

---

package.json

Npm has wrong directory structure

fix(build): fix incorrect npm

---

package.json

Copy package.json to dist so that the semantic version is correct in npm

fix(build): copy version to dist

---

.travis.yml

Do not cd to dist. Doing that in semantic-release

fix(deploy): releasing from wrong directory

---

.travis.yml
scripts/ci/after-success.sh

Semantic release exiting on error

fix(build): semantic release should exit on error

---

integration/package.json
src/demo/app/core/manifest-service/manifest.service.ts

fix: relative manifest paths

---

build.js
integration/.angular-cli.json
integration/.gitignore
integration/e2e/templates/imposters.ejs
package.json

Openseadragon as peer dependency

BREAKING CHANGE:  openseadragon as peer dependency

---

src/demo/assets/fixtures/presentation/2/simple-rtl-manifest.json

Changed right-to-left manifest to child book

style: changed right-to-left manifest

---

src/demo/app/core/custom-http.ts

Adding withCredentials for nb.no

fix: withCredentials for nb.no

---

.travis.yml

Build times out because no output was received

build: build times out because no output was received

---

README.md

docs: Conventional Commits badge

---

integration/e2e/features/rights-notices.feature
integration/e2e/features/viewer.feature
integration/package.json
integration/protractor.conf.js
integration/remote-browsers.js

@mobile runs only on Android Emulator and iPhone Simulator

test(e2e): @mobile test only on android emulator and iphone Simulator

---

.travis.yml

ci: change to node v7

---

integration/e2e/helpers/cucumber.config.ts
integration/e2e/helpers/utils.ts
integration/e2e/pages/metadata.po.ts
integration/e2e/pages/viewer.po.ts
integration/e2e/step-definitions/content-dialog.steps.ts
integration/e2e/step-definitions/rights-notices.steps.ts
integration/e2e/step-definitions/viewer-page.steps.ts
integration/package.json
integration/protractor.conf.js
integration/yarn.lock
karma.conf.js

Karma and local e2e running Headless Chrome

test: headless testing in chrome

---

integration/yarn.lock
src/lib/src/content-search-dialog/content-search-dialog-config-strategy.ts
src/lib/src/content-search-dialog/content-search-dialog.component.html
yarn.lock

* Setting focus on the search box
* Esc key to close dialog
* Use tab to navigate to content  search result
* Enter key on hit goes to search result

feat: keyboard navigation in content search

---

integration/yarn.lock
src/lib/src/contents-dialog/contents-dialog-config-strategy.ts
src/lib/src/contents-dialog/contents-dialog.component.html
yarn.lock

* Setting focus on metadata tab
* Esc key to close dialog

feat: keyboard navigation in contents

---

src/lib/index.ts
src/lib/src/core/mode-service/mode.service.ts
src/lib/src/viewer/viewer.component.spec.ts
src/lib/src/viewer/viewer.component.ts

pageModeChanged emits when an page mode event is fired

feat: emit page mode change

---

yarn.lock

yarn.lock contains old merge conflict https://github.com/NationalLibraryOfNorway/ngx-mime/blob/master/yarn.lock#L849

fix: recreate and update yarn lockfile to fix previous merge problem

---

src/lib/src/core/viewer-service/viewer.service.ts

Zooming in where first finger is touching. This seems to be the standard elsewhere. When pinching inwards (zooming out) use center-point between the fingers like before

feat: better pinch-zooming

---

src/lib/src/viewer/viewer-footer/viewer-footer.component.scss

fix: single long press causes error on android device

---

src/lib/src/core/viewer-service/swipe-utils.spec.ts
src/lib/src/core/viewer-service/swipe-utils.ts
src/lib/src/core/viewer-service/viewer.service.ts

Special case where speed = 0 seems to fix this issue

fix: NGXMIM-38: Going outside right side when zoomed in

---

src/lib/src/core/intl/viewer-intl.no_nb.ts

fix: previousHitLabel and nextHitLabel for intl nonb

---

src/lib/src/core/page-service/page-service.ts
src/lib/src/core/viewer-service/viewer.service.ts
src/lib/src/rxjs-extension.ts
src/lib/src/viewer/viewer-footer/page-navigator/page-navigator.component.spec.ts
src/lib/src/viewer/viewer-footer/page-navigator/page-navigator.component.ts
src/lib/src/viewer/viewer.component.spec.ts

Changed from throttle to sample

fix: page numbers is not always updated

---

src/lib/src/core/mime-viewer-config.ts
src/lib/src/core/models/options.ts
src/lib/src/core/viewer-service/viewer.service.ts
src/lib/src/viewer/viewer.component.ts

feat: cors support

---

src/lib/src/core/mime-viewer-config.ts
src/lib/src/core/models/options.ts
src/lib/src/core/viewer-service/viewer.service.ts

This PR allow for tiles to be loaded with custom headers
fixes #129

Add options for loading tiles with custom AJAX request headers

---

src/lib/src/core/iiif-content-search-service/iiif-content-search.service.ts
src/lib/src/viewer/viewer.component.spec.ts
src/lib/src/viewer/viewer.component.ts

Emit content search query changes

---

integration/package.json
integration/protractor.conf.js
integration/scripts/protractor.sh
integration/yarn.lock
package.json

```
npm run integration:firefox
```
Fixes #141

test: local integration testing with firefox

---

src/lib/index.ts
src/lib/src/viewer/viewer.component.spec.ts
src/lib/src/viewer/viewer.component.ts

feat: emit manifest model on change

---

src/lib/src/core/page-service/page-service.spec.ts
src/lib/src/core/page-service/page-service.ts

fix: no pages are displayed on load

---

src/lib/src/viewer/viewer-header/viewer-header.component.html

style: tooltip should be displayed under the title

---

src/lib/src/core/viewer-service/viewer.service.ts
src/lib/src/core/viewer-service/zoom-utils.spec.ts
src/lib/src/core/viewer-service/zoom-utils.ts

fix: constraining to max zoom

---

src/lib/src/core/models/options.ts
src/lib/src/core/viewer-service/page-mask.ts
src/lib/src/viewer/viewer.component.spec.ts

fix:page mask when zooming on page edge

---

integration/e2e/features/content-search.feature
integration/e2e/pages/content-search.po.ts
integration/e2e/step-definitions/content-search.steps.ts
src/lib/src/content-search-dialog/content-search-dialog.component.spec.ts
src/lib/src/content-search-dialog/content-search-dialog.component.ts
src/lib/src/contents-dialog/table-of-contents/table-of-contents.component.spec.ts
src/lib/src/core/builders/search-result.builder.ts
src/lib/src/core/iiif-content-search-service/iiif-content-search.service.ts
src/lib/src/core/models/search-result.ts
src/lib/src/core/viewer-service/viewer.service.ts
src/lib/src/test/iiif-content-search-service-stub.ts
src/lib/src/test/viewer-service-mock.ts
src/lib/src/viewer/osd-toolbar/osd-toolbar.component.spec.ts
src/lib/src/viewer/viewer-footer/content-search-navigator/content-search-navigator.component.spec.ts
src/lib/src/viewer/viewer-footer/content-search-navigator/content-search-navigator.component.ts
src/lib/src/viewer/viewer-footer/page-navigator/page-navigator.component.spec.ts
src/lib/src/viewer/viewer.component.scss

feat: highlighting current hit differently

---

integration/e2e/features/view-switch.feature
integration/e2e/pages/content-search.po.ts
integration/e2e/pages/contents.po.ts
integration/e2e/step-definitions/content-dialog.steps.ts
integration/e2e/step-definitions/content-search.steps.ts
src/lib/src/viewer/viewer.component.ts

This feature was commented out by a mistake
Fixes #172

fix: close dialogs when switching to page mode

---

integration/e2e/pages/viewer.po.ts

await on getting page overlays
Fixes #173

test(e2e): fix flaky e2e test (two page display)

---

.travis.yml
integration/package.json
package.json

build: should use yarn in ci build

---

src/lib/src/viewer/viewer-footer/content-search-navigator/content-search-navigator.component.spec.ts
src/lib/src/viewer/viewer-footer/content-search-navigator/content-search-navigator.component.ts

feat: skip second page with hits when in two page display mode

---

integration/yarn.lock
src/lib/src/core/iiif-content-search-service/iiif-content-search.service.spec.ts
src/lib/src/core/iiif-content-search-service/iiif-content-search.service.ts
src/lib/src/core/models/search-result.ts
yarn.lock

feat: empty search string should empty search result

---

src/lib/src/contents-dialog/contents-dialog.component.html
src/lib/src/contents-dialog/contents-dialog.component.spec.ts
src/lib/src/contents-dialog/contents-dialog.component.ts
src/lib/src/core/models/manifest.ts

feat: hide empty toc

---

src/lib/src/contents-dialog/contents-dialog.component.html
src/lib/src/contents-dialog/contents-dialog.component.ts
src/lib/src/contents-dialog/contents-dialog.service.ts
src/lib/src/core/models/viewerState.ts
src/lib/src/viewer/viewer.component.ts

fix: toc is not reopened after returning to dashboard mode

---

.prettierignore
package.json
prettier.config.js
tslint.json
yarn.lock

Prettier is an opinionated code formatter

feat: added prettier code formatter

---

src/lib/src/core/access-keys-handler-service/access-keys.service.ts
src/lib/src/core/viewer-service/go-to-canvas-group-strategy.ts

```
[x] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
[ ] application / infrastructure changes
```
Issue Number: fixes #217
Page Up and Page Down keys change page also when viewer is in zoomed in mode
```
[ ] Yes
[x] No
```

fix: Page Up and Page Down keys should change page when zoomed in

---

integration/yarn.lock
src/lib/src/core/canvas-service/canvas-service.ts
src/lib/src/core/viewer-service/viewer.service.ts
src/lib/src/test/canvas-service-stub.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number:
Fixes #219
```
[ ] Yes
[x] No
```

fix: number of pages is wrong on two page display

---

src/demo/app/core/manifest-service/manifest.service.ts
src/demo/assets/fixtures/presentation/2/static-image-manifest.json
src/lib/src/core/viewer-service/iiif-tile-source-strategy.spec.ts
src/lib/src/core/viewer-service/iiif-tile-source-strategy.ts
src/lib/src/core/viewer-service/static-image-tile-source-strategy.spec.ts
src/lib/src/core/viewer-service/static-image-tile-source-strategy.ts
src/lib/src/core/viewer-service/tile-source-strategy-factory.ts
src/lib/src/core/viewer-service/tile-source-strategy.ts
src/lib/src/core/viewer-service/viewer.service.ts

```
[ ] Bugfix
[X] Feature
```
Issue Number: #223 
Support for static or non-IIIF image viewing
```
[ ] Yes
[X] No
```
Fixes #223

feat: support for static or non-IIIF image viewing

---

scripts/saucelabs/start-tunnel.sh

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[X] No
```

build: update saucelabs-connect to 4.5.1

---

libs/ngx-mime/src/lib/viewer/viewer.component.ts

fix: Safari is missing DragEvent

---

libs/ngx-mime/src/lib/core/fullscreen-service/fullscreen.service.ts

fix: fullscreen in chrome 71

---

libs/ngx-mime/src/lib/core/viewer-service/viewer.service.ts
libs/ngx-mime/src/lib/core/viewer-service/zoom-strategy.ts

```
[ ] Bugfix
[X] Feature
```
Fits current page into viewport
Show partial previous and next page in dashboard view
```
[ ] Yes
[X] No
```

feat: show partial previous and next page in dashboard view

---

scripts/release/release.sh

```
[ ] Bugfix
[ ] Feature
```
Wrong path in release script
Fixed path
```
[ ] Yes
[X] No
```

build: fix release path

---

libs/ngx-mime/src/lib/core/intl/viewer-intl.no_nb.ts
libs/ngx-mime/src/lib/core/intl/viewer-intl.ts
libs/ngx-mime/src/lib/viewer/viewer-footer/canvas-group-navigator/canvas-group-navigator.component.html

```
[ ] Bugfix
[ ] Feature
```
Issue Number: https://github.com/NationalLibraryOfNorway/ngx-mime/issues/260
```
[ ] Yes
[X] No
```

fix: added aria-label for pagenavigator

---

apps/integration-e2e/features/accessibility.feature
apps/integration-e2e/pages/viewer.po.ts
apps/integration-e2e/step-definitions/accessibility.steps.ts
apps/integration-e2e/step-definitions/viewer-page.steps.ts
apps/integration-e2e/templates/a-non-attribution-book.ejs
apps/integration-e2e/templates/imposters.ejs
apps/integration/src/app/app.component.html
package.json
yarn.lock

```
[ ] Bugfix
[X] Feature
```
Missing accessibility tests
Added accessibility tests
```
[ ] Yes
[X] No
```
"Accessibility in contents dialog" and "Accessibility in search dialog" is ignored. They must be included when issues is fixed.

test(e2e): added a11y feature

---

apps/demo/src/app/app.component.html
apps/demo/src/app/core/navbar/navbar.component.html
apps/demo/src/app/core/navbar/theme-picker/theme-picker.component.html
apps/demo/src/app/core/sidenav/sidenav.component.html
apps/demo/src/app/core/sidenav/sidenav.component.scss

```
[X] Bugfix
[ ] Feature
```
Demo webapp does not follow accessibility guidelines. It makes it hard to use accessibility plugins to test if the viewer is following all of the accessibility guidelines.
Demo webapp follows accessibility guidelines
```
[ ] Yes
[X] No
```

fix(demo): fixed a11y issues

---

apps/demo/src/app/app.module.ts

```
[X] Bugfix
[ ] Feature
```
Issue Number: https://github.com/NationalLibraryOfNorway/ngx-mime/issues/269
Dialogs are now visible and functional in fullscreen mode
```
[ ] Yes
[X] No
```

fix: use fullscreenoverlaycontainer

---

libs/ngx-mime/src/lib/content-search-dialog/content-search-dialog.component.html
libs/ngx-mime/src/lib/content-search-dialog/content-search-dialog.component.spec.ts

```
[x] Bugfix
[ ] Feature
```
Close, Search and Clear buttons cannot be reached by keyboard navigation. 
Clear button is present even if there is nothing to clear.
Input element doesn't have any label
All buttons can be reached with keyboard navigation.
Clear button is only present if input has value.
Input element is labelled by the Search button.
```
[ ] Yes
[x] No
```

Improve accessibility for content search dialog

---

scripts/ci/build-and-test.sh

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix: override libs build

---

package.json

```
[ ] Bugfix
[ ] Feature
```
`yarn e2e` builds a invalid library using angular cli
`yarn e2e` builds a valid library using ng-packgr
```
[ ] Yes
[X] No
```

fix(build): e2e is using wrong build step

---

libs/ngx-mime/src/lib/attribution-dialog/attribution-dialog.component.scss

```
[X] Bugfix
[ ] Feature
```
Attribution dialog layout on IE11 is broken
Fixes attribution dialog layout on IE11
```
[ ] Yes
[X] No
```

fix: attribution dialog layout ie11

---

libs/ngx-mime/src/index.ts
libs/ngx-mime/src/lib/attribution-dialog/attribution-dialog.service.ts
libs/ngx-mime/src/lib/core/intl/help-intl.lt.ts
libs/ngx-mime/src/lib/core/intl/viewer-intl.lt.ts

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
Additional optional provider instance.
```
Currently, tooltips and labels are only available in English or Norwegian.
Added a Lithuanian instance of MimeViewerIntl.
```
[ ] Yes
[x] No
```

feat: Added lithuanian label translations

---

libs/ngx-mime/src/lib/viewer/viewer-header/viewer-header.component.html

jira task: https://www.nb.no/jira/browse/NBWEB-820

Changed help label

---

libs/ngx-mime/src/lib/core/access-keys-handler-service/access-keys.service.ts
libs/ngx-mime/src/lib/core/canvas-group-position/calculate-canvas-group-position-strategy.ts
libs/ngx-mime/src/lib/core/canvas-group-position/calculate-canvas-group-position-utils.spec.ts
libs/ngx-mime/src/lib/core/canvas-group-position/calculate-canvas-group-position-utils.ts
libs/ngx-mime/src/lib/core/canvas-group-position/one-page-calculate-page-position-strategy.ts
libs/ngx-mime/src/lib/core/canvas-group-position/two-page-calculate-page-position-strategy.ts
libs/ngx-mime/src/lib/core/intl/help-intl.lt.ts
libs/ngx-mime/src/lib/core/intl/help-intl.no_nb.ts
libs/ngx-mime/src/lib/core/intl/help-intl.ts
libs/ngx-mime/src/lib/core/intl/viewer-intl.lt.ts
libs/ngx-mime/src/lib/core/intl/viewer-intl.no_nb.ts
libs/ngx-mime/src/lib/core/intl/viewer-intl.ts
libs/ngx-mime/src/lib/core/mime-dom-helper.ts
libs/ngx-mime/src/lib/core/models/AccessKeys.ts
libs/ngx-mime/src/lib/core/viewer-service/viewer.service.spec.ts
libs/ngx-mime/src/lib/core/viewer-service/viewer.service.ts
libs/ngx-mime/src/lib/help-dialog/help-dialog.component.html
libs/ngx-mime/src/lib/viewer/osd-toolbar/osd-toolbar.component.html
libs/ngx-mime/src/lib/viewer/osd-toolbar/osd-toolbar.component.ts

```
[ ] Bugfix
[x] Feature
```
Issue Number: #290 
Supports clockwise rotation. 
```
[ ] Yes
[x] No
```

feat: page rotation

---

apps/elements/src/theme.scss
apps/integration-e2e/pages/content-search.po.ts
libs/ngx-mime/src/lib/content-search-dialog/content-search-dialog.component.html
libs/ngx-mime/src/lib/contents-dialog/metadata/metadata.component.theme.scss

```
[X] Bugfix
[X] Feature
```
Issue Number: #306
- Dark mode for elements
- Fixes missing custom theme for components
```
[ ] Yes
[X] No
```
Fixes https://github.com/NationalLibraryOfNorway/ngx-mime/issues/306
1. Starte application ```yarn start:elements```
2. Add class ngx-mime-dark-theme to body for testing

feat: dark theme for elements

---

package.json
yarn.lock

```
[ ] Bugfix
[ ] Feature
[x] Build related changes
```
'node-sass' usage is deprecated and will be removed in a future major version.
'node-sass' usage is removed.
```
[ ] Yes
[x] No
```

fix: removed deprecated node-sass

---

CONTRIBUTING.md
PULL_REQUEST_TEMPLATE.md
README.md
libs/ngx-mime/src/lib/core/canvas-service/canvas-service.ts
libs/ngx-mime/src/lib/core/viewer-service/viewer.service.spec.ts
nx.json
scripts/release/release.sh

```
[ ] Bugfix
[ ] Feature
```
The initial branch name, ‘master’, is offensive to some people. Master has been renamed to main
Change branch name master to main
```
[ ] Yes
[X] No
```

chore: rename master branch to main

---

apps/demo/src/test.ts
apps/elements/src/polyfills.ts
apps/elements/src/test.ts
apps/integration/src/app/app.module.ts
apps/integration/src/test.ts
libs/ngx-mime/src/lib/viewer/viewer.component.spec.ts
libs/ngx-mime/src/test.ts

```
[X] Bugfix
[ ] Feature
```
Wallabyjs does not work
Wallabyjs runs as espected
```
[ ] Yes
[X] No
```

fix: wallabyjs

---

apps/demo/src/index.html
apps/elements/src/index.html
apps/integration/src/index-elements.html
apps/integration/src/index.html

```
[X] Bugfix
[ ] Feature
```
Apps is missing material typography styles. 
Font styles may therefore look different than they should
Added Material Typography
```
[ ] Yes
[X] No
```

fix: apps is missing material typography styles

---

apps/demo/src/app/app.component.scss
libs/ngx-mime/src/lib/viewer/viewer-header/viewer-header.component.scss

```
[X] Bugfix
[ ] Feature
```
There is an empty space above header in demo app
Header toolbar changes size on mobile devices
```
[ ] Yes
[X] No
```

fix(demo): correct header size on mobile devices

---

apps/integration-e2e/features/access-keys.feature
apps/integration-e2e/pages/viewer.po.ts
libs/ngx-mime/src/lib/core/access-keys-handler-service/access-keys.service.ts
libs/ngx-mime/src/lib/core/intl/help-intl.lt.ts
libs/ngx-mime/src/lib/core/intl/help-intl.no_nb.ts
libs/ngx-mime/src/lib/core/intl/help-intl.ts
libs/ngx-mime/src/lib/core/models/AccessKeys.ts
libs/ngx-mime/src/lib/help-dialog/help-dialog.component.html

```
[ ] Bugfix
[X] Feature
```
There is no access key for show/hide recognized text conent
't' toggles recognized text content
```
[ ] Yes
[X] No
```

feat: access key for recognized text content

---

scripts/release/release.sh

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix: release script

---

libs/ngx-mime/src/lib/content-search-dialog/content-search-dialog.component.html
libs/ngx-mime/src/lib/content-search-dialog/content-search-dialog.component.scss

Fixes #372
```
[X] Bugfix
[ ] Feature
```
Issue Number: #372 
```
[ ] Yes
[X] No
```

fix: search dialog title should be h1

---

scripts/saucelabs/start-tunnel.sh

```
[ ] Bugfix
[ ] Feature
[x] CI related changes
```
```
[ ] Yes
[x] No
```

chore: update Sauce Connect Proxy

---

libs/ngx-mime/src/lib/core/viewer-service/options.factory.ts

```
[ ] Bugfix
[X] Feature
```
Issue Number: #391 
This allows the user to zoom further into the pages
```
[ ] Yes
[X] No
```

feat: change maxZoomPixelRatio to 5

---

apps/integration-e2e/features/zoom-to-current-page-size.feature
apps/integration-e2e/step-definitions/zoom-to-current-page-size.steps.ts
libs/ngx-mime/src/lib/core/canvas-service/canvas-service.ts
libs/ngx-mime/src/lib/core/models/canvas-groups.ts
libs/ngx-mime/src/lib/core/viewer-service/viewer.service.ts
libs/ngx-mime/src/lib/core/viewer-service/zoom-strategy.ts

```
[ ] Bugfix
[X] Feature
```
Issue Number: #388 
```
[ ] Yes
[X] No
```

feat: zoom to current page size in dashboard mode

---

.circleci/config.yml

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[X] No
```

build: legacy Convenience Image Deprecation

---

angular.json

```
[ ] Bugfix
[ ] Feature
```
Angular DevTools is a Chrome extension that provides debugging and profiling capabilities for Angular applications. It does not work in demo app.
Added development profile
```
[ ] Yes
[X] No
```

build: development

---

libs/ngx-mime/src/lib/content-search-dialog/content-search-dialog.component.html
libs/ngx-mime/src/lib/viewer/viewer-footer/canvas-group-navigator/canvas-group-navigator.component.html
libs/ngx-mime/src/lib/viewer/viewer-footer/canvas-group-navigator/canvas-group-navigator.component.spec.ts

```
[X] Bugfix
[ ] Feature
```
Issue Number: https://github.com/NationalLibraryOfNorway/ngx-mime/issues/413
Slider navigation with arrowkeys are working again in RTL manifests
```
[ ] Yes
[X] No
```

fix: changed keyup events in templates to keydown

---

libs/ngx-mime/src/lib/core/viewer-service/options.factory.ts

```
[x] Bugfix
[ ] Feature
```
Rotating object on Mac is currently not possible
Rotating object in the viewer should now be possible again on Mac devices
```
[ ] Yes
[x] No
```

fix: should now rotate on Mac IOS but not handheld IOS

---

libs/ngx-mime/src/lib/core/intl/help-intl.lt.ts
libs/ngx-mime/src/lib/core/intl/help-intl.no_nb.ts
libs/ngx-mime/src/lib/core/intl/help-intl.ts
libs/ngx-mime/src/lib/help-dialog/help-dialog.component.html

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
Shift-S keyboard shortcut is not listed in help dialog
Shift-S keyboard shortcut is listed in help dialog
```
[ ] Yes
[x] No
```

fix: add help text for Shift-S

---

libs/ngx-mime/src/lib/view-dialog/view-dialog-config-strategy.ts

```
[ ] Bugfix
[X] Feature
```
Narrower view dialog
```
[ ] Yes
[X] No
```

feat: narrower view dialog

---

.circleci/config.yml
apps/integration-e2e/pages/viewer.po.ts
libs/ngx-mime/src/lib/view-dialog/view-dialog.component.html
package.json
scripts/saucelabs/start-tunnel.sh

```
[X] Bugfix
[ ] Feature
```
Mobile tests fails
- Mobile tests fixed
- Faster circleci image
- Updated saucelab connector
```
[ ] Yes
[X] No
```

fix(e2e): tests

---

libs/ngx-mime/src/lib/core/viewer-layout-service/viewer-layout-service.spec.ts
libs/ngx-mime/src/lib/viewer/recognized-text-content/recognized-text-content.component.spec.ts
libs/ngx-mime/src/lib/viewer/viewer-header/viewer-header.component.spec.ts

```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
```
[ ] Yes
[x] No
```

fix: various jasmine 4.0 deprecations

---

README.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

chore: added LambdaTest badge

---

libs/ngx-mime/src/lib/core/builders/alto/alto.builder.spec.ts
libs/ngx-mime/src/lib/core/builders/alto/page.builder.ts
libs/ngx-mime/src/lib/core/builders/alto/print-space.builder.ts
libs/ngx-mime/src/lib/test/testAltos.ts

```
[X] Bugfix
[ ] Feature
```
Recognized text is not displayed if margins is missing
Handle empty margins
```
[ ] Yes
[X] No
```

fix: handle empty margins in recognized text

---

libs/ngx-mime/src/lib/contents-dialog/metadata/metadata.component.theme.scss

```
[ ] Bugfix
[X] Feature
```
Title in metadata dialog should have themable colors
Title in metadata dialog now uses forground text palett
```
[ ] Yes
[X] No
```

feat: themed metadata title

---

libs/ngx-mime/src/lib/attribution-dialog/attribution-dialog.component.scss

```
[X] Bugfix
[ ] Feature
```
Attribution dialog is not transparent
Issue Number: #443
Attribution dialog is transparent
```
[ ] Yes
[X] No
```

fix: transparent attribution dialog

---

dist/libs/@nationallibraryofnorway/ngx-mime/package.json
nx.json
package.json
scripts/release/release.sh

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[X] No
```

build: fix cache problems

---

scripts/release/release.sh

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

build: added git commit to release

---

package.json
yarn.lock

```
[ ] Bugfix
[ ] Feature
```
Moved Tailwind CSS to dev
```
[ ] Yes
[X] No
```

build: moved tailwindcss dependency to devDependencies

---

libs/ngx-mime/src/lib/viewer/viewer-footer/content-search-navigator/content-search-navigator.component.html

```
[X] Bugfix
[ ] Feature
```
Adjust content search navigator width from 270px to 275px
```
[ ] Yes
[X] No
```

fix: adjust content search navigator width from 270px to 275px

---

libs/ngx-mime/src/lib/viewer/recognized-text-content/recognized-text-content.component.html

```
[X] Bugfix
[ ] Feature
```
Recognized text is left aligned, but should have been centered
Recogniex text is centered
```
[ ] Yes
[X] No
```

fix: ensure proper text centering for recognized text content

---

libs/ngx-mime/src/lib/core/viewer-service/iiif-tile-source-strategy.ts

```
[X] Bugfix
[ ] Feature
```
No need for this workaround after change made in openseadragon (https://github.com/openseadragon/openseadragon/pull/2055)
```
[ ] Yes
[X] No
```

fix: remove  tileOverlap workaround

---

.circleci/config.yml

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

build: set no_output_timeout to 60m

---

CHANGELOG.md

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix: incorrect formatting in CHANGELOG.md

---

apps/integration-e2e/src/pages/content-search.po.ts
apps/integration-e2e/src/step-definitions/content-search.steps.ts
jest.preset.js
libs/ngx-mime/src/lib/content-search-dialog/content-search-dialog.component.html
scripts/ci/build-and-test.sh

…proceeding
Fixes #489
```
[X] Bugfix
[ ] Feature
```
Issue Number: #489 
The tests is waiting for content search result to be visible
```
[ ] Yes
[X] No
```

test(e2e):  wait for the content search results to be visible before proceeding

---

.eslintrc.json
apps/demo/src/app/core/navbar/theme-picker/theme-picker.component.html
apps/demo/src/app/core/sidenav/sidenav.component.html
apps/demo/src/app/viewer/viewer.component.html
apps/integration/src/app/viewer/viewer.component.html
libs/ngx-mime/src/lib/canvas-group-dialog/canvas-group-dialog.component.html
libs/ngx-mime/src/lib/content-search-dialog/content-search-dialog.component.html
libs/ngx-mime/src/lib/help-dialog/help-dialog.component.html
libs/ngx-mime/src/lib/information-dialog/information-dialog.component.html
libs/ngx-mime/src/lib/information-dialog/metadata/metadata.component.html
libs/ngx-mime/src/lib/information-dialog/table-of-contents/table-of-contents.component.html
libs/ngx-mime/src/lib/view-dialog/icon/icon.component.html
libs/ngx-mime/src/lib/view-dialog/view-dialog.component.html
libs/ngx-mime/src/lib/viewer/osd-toolbar/osd-toolbar.component.html
libs/ngx-mime/src/lib/viewer/recognized-text-content/recognized-text-content.component.html
libs/ngx-mime/src/lib/viewer/viewer-footer/canvas-group-navigator/canvas-group-navigator.component.html
libs/ngx-mime/src/lib/viewer/viewer-footer/content-search-navigator/content-search-navigator.component.html
libs/ngx-mime/src/lib/viewer/viewer-footer/viewer-footer.component.html
libs/ngx-mime/src/lib/viewer/viewer-header/viewer-header.component.html
libs/ngx-mime/src/lib/viewer/viewer-header/viewer-header.component.ts
libs/ngx-mime/src/lib/viewer/viewer.component.html

Migrated templates to the new flow control syntax introduced in Angular 17.
```
[ ] Bugfix
[ ] Feature
[X] Code style update (formatting, local variables)
```
NGX-mime is currently using the old template syntax for flow control that is pre-Angular 17.
Updated templates and components to use the new flow control syntax introduced in Angular 17. Improved code readability and maintainability by leveraging the new syntax.
```
[ ] Yes
[X] No
```

refactor: update to Angular 17 flow control syntax

---

libs/ngx-mime/src/lib/core/viewer-service/viewer.service.ts
libs/ngx-mime/src/lib/viewer/viewer.component.ts

```
[X] Bugfix
[ ] Feature
```
Pages do not fit the canvas correctly when swiping.
This commit resolves an issue where pages were not correctly zooming to fit within the viewer during a swipe action, ensuring a better user experience and accurate page display.
```
[ ] Yes
[X] No
```

fix: ensure proper page zoom on swipe

---

apps/demo/src/theme.scss
apps/demo/src/themes/theming.scss
apps/elements/src/styles.scss
apps/integration/src/styles.scss
dist/libs/@nationallibraryofnorway/ngx-mime/package.json

```
[X] Bugfix
[ ] Feature
```
Build failure due to incorrect import paths for ngx-mime theme.
Build completes successfully after correcting ngx-mime theme import paths
```
[ ] Yes
[X] No
```

fix: update ngx-mime theme import paths and remove unused theme file

---

libs/ngx-mime/ngx-mime-theme.scss

```
[X] Bugfix
[ ] Feature
```
Currently, links are not underlined, and their color is set to accent. This does not fully comply with the Material Design 3 guidelines, which emphasize better contrast and visibility for links.
This update aligns the ngx-mime dialog background and link styling with the Material Design 3 specification to improve visibility and consistency.
Changes:
- Updated dialog background to use surface-container-high for better contrast and …

fix(ngx-mime): update dialog background and link styling to comply with Material Design 3
