NationalLibraryOfNorway/ngx-mime

package.json, scripts/ci/after-success.sh
Semantic release was running in root directory. Should be running in dist
=> fix(build): semantic release fix

scripts/ci/after-success.sh
Do not run semantic-release from dist folder
=> fix(build): still running from dist folder

src/lib/src/attribution-dialog/attribution-dialog.service.ts
Temporarily fix for https://github.com/angular/material2/issues/7438
Sleeping for 1 sec while waiting for angular material animations to finish closing previous dialog
=> fix: material dialog bug

src/lib/src/core/models/viewer-options.ts, src/lib/src/core/viewer-service/page-zoomed-mode-calculate-next-page-strategy.spec.ts, src/lib/src/core/viewer-service/page-zoomed-mode-calculate-next-page-strategy.ts, src/lib/src/core/viewer-service/swipe-utils.spec.ts, src/lib/src/core/viewer-service/swipe-utils.ts, src/lib/src/core/viewer-service/viewer.service.ts
- Better panning in zoomed-in-mode; Stop viewport from panning slightly outside sides of pages
- Remove speed-criteria from zoomed-in-mode: This criteria isn't necessary in my opinion, and also doesn't exist on Play Books
=> fix: better panning in zoomed-in-mode + remove speed-criteria from zoomed-mode when calculating next page

src/lib/src/core/models/options.ts
Setting constrainDuringPan to false seems to be the easiest fix for this issue. Now the page first/last pages bounces back when it hits the edges
=> fix: NGXMIM-33 - viewport doesn't pan on first/last page

src/lib/src/core/viewer-service/swipe-utils.spec.ts, src/lib/src/core/viewer-service/swipe-utils.ts, src/lib/src/core/viewer-service/viewer.service.ts
Added calculation for direction inside right / left semicircle to stop the viewer from panning horizontally past the edges
=> fix: NGXMIM-34 - Panning does not stop when hitting the edge of the page if panning diagonal

src/lib/src/core/viewer-service/viewer.service.ts
Remove setting to page-mode on goToHomeZoom() fixes this issue
=> fix: page no longer zooms out before going to next page in zoomed in mode

src/lib/src/attribution-dialog/attribution-dialog.service.ts, src/lib/src/content-search-dialog/content-search-dialog.service.ts, src/lib/src/contents-dialog/contents-dialog.service.ts, src/lib/src/viewer/viewer.component.spec.ts, src/lib/src/viewer/viewer.component.ts
Fixes "Uncaught Error: ViewDestroyedError: Attempt to use a destroyed view: detectChanges
at node_modules/zone.js/dist/zone.js:195"
Probably the attributes dialog that runs animations after the view is destroyed
=> fix: cleanup viewer on destroy

src/lib/src/core/viewer-service/page-mask.ts
Removed dependency on viewport coordinates from page-mask setCenter() method.
=> fix: page-mask center is calculated incorrectly during pan events

src/lib/src/viewer/viewer.component.spec.ts
Make sure viewer stays on same page after layout change and don't return
to initial @Input() canvasIndex.
=> test(viewer-component): remain on tile

src/lib/src/viewer/osd-toolbar/osd-toolbar.component.scss
=> fix: OSD toolbar takes full width in IE11

src/lib/src/core/iiif-content-search-service/iiif-content-search.service.ts
Fixes 
WARNING: /home/travis/build/NationalLibraryOfNorway/ngx-mime/src/lib/src/core/iiif-content-search-service/iiif-content-search.service.ts[77, 23]: throw is deprecated: In favor of throwError creation function: import { throwError } from 'rxjs';
=> fix: fixing lint error

integration/e2e/features/slider-navigation-in-dashboard-view.feature, integration/e2e/pages/viewer.po.ts, integration/e2e/step-definitions/content-search.steps.ts, integration/e2e/step-definitions/layout.steps.ts, integration/e2e/step-definitions/view-switch.steps.ts, integration/package.json, package.json, src/demo/app/viewer/viewer.component.ts, src/lib/src/core/mime-viewer-config.ts, src/lib/src/core/viewer-service/go-to-canvas-group-strategy.spec.ts, src/lib/src/core/viewer-service/go-to-canvas-group-strategy.ts, src/lib/src/core/viewer-service/viewer.service.ts, src/lib/src/core/viewer-service/zoom-strategy.ts, src/lib/src/viewer/viewer-footer/canvas-group-navigator/canvas-group-navigator.component.html, src/lib/src/viewer/viewer.component.spec.ts
To use it 
```
public config = new MimeViewerConfig({
preserveZoomOnPageChange: true
});
```
Default is false
=> feat: preserve zoom level on page change

apps/integration-e2e/remote-browsers.js
```
[ ] Bugfix
[ ] Feature
```
Firefox v63 opens a update dialog after 4 minutes that causes e2e tests to fail
Forcing Firefox v62
```
[ ] Yes
[X] No
```
=> test(e2e): forcing firefox v62

libs/ngx-mime/src/lib/viewer/viewer-footer/canvas-group-navigator/canvas-group-navigator.component.html
```
[X] Bugfix
[ ] Feature
```
Navigation button label is not horizontally aligned, and gap between pagenumber and number of pages is not equal
- Navigation button label is horizontally aligned. 
- Gap between pagenumber and number of pages equal
```
[ ] Yes
[X] No
```
=> fix: align navigation button label

apps/integration/src/app/viewer/viewer.component.spec.ts, libs/ngx-mime/src/lib/core/viewer-service/zoom-strategy.ts
Should show show partial previous and next page in dashboard view
```
[ ] Bugfix
[X] Feature
```
Pages in dashboard view is unnecessary small when viewport is very wide
Pages can have fulll viewport heigh
```
[ ] Yes
[X] No
```
=> feat: better scaling in dashboard view

libs/ngx-mime/src/lib/viewer/osd-toolbar/osd-toolbar.component.ts
```
[X] Bugfix
[ ] Feature
```
OSD toolbar is focusable in it's hidden state and readable by screenreaders.
Issue Number: https://github.com/NationalLibraryOfNorway/ngx-mime/issues/263
OSD toolbar is set to display: none when it has state 'hidden'. No longer focusable when offscreen.
```
[ ] Yes
[X] No
```
=> fix(a11y): added 'display: none' to OSD toolbar in hidden state

apps/integration-e2e/pages/viewer.po.ts, libs/ngx-mime/src/lib/attribution-dialog/attribution-dialog.component.html, libs/ngx-mime/src/lib/attribution-dialog/attribution-dialog.component.scss, libs/ngx-mime/src/lib/attribution-dialog/attribution-dialog.component.spec.ts, libs/ngx-mime/src/lib/attribution-dialog/attribution-dialog.component.ts, libs/ngx-mime/src/lib/attribution-dialog/attribution-dialog.service.ts, libs/ngx-mime/src/lib/core/intl/viewer-intl.no_nb.ts, libs/ngx-mime/src/lib/core/intl/viewer-intl.ts, libs/ngx-mime/src/lib/core/mime-dom-helper.ts, libs/ngx-mime/src/lib/viewer/test-host.component.ts, libs/ngx-mime/src/lib/viewer/viewer.component.html, libs/ngx-mime/src/lib/viewer/viewer.component.spec.ts, libs/ngx-mime/src/lib/viewer/viewer.component.ts
```
[ ] Bugfix
[X] Feature
```
Attribution dialog is missing arial-label on close button
Issue Number: #259 
- Aria label is set correctly
- Esc to close dialog
```
[ ] Yes
[X] No
```
=> feat(a11y): fix attribute dialog

libs/ngx-mime/src/lib/content-search-dialog/content-search-dialog.component.html, libs/ngx-mime/src/lib/contents-dialog/contents-dialog.component.html
```
[ ] Bugfix
[ ] Feature
```
Issue Number: https://github.com/NationalLibraryOfNorway/ngx-mime/issues/261
```
[ ] Yes
[X] No
```
Changed [attr.aria-label] -> [aria-label] for buttons with matDialogClose
=> fix: correct aria-label for dialogclose buttons

apps/integration-e2e/pages/viewer.po.ts, apps/integration-e2e/step-definitions/fullscreen.steps.ts, libs/ngx-mime/src/lib/core/access-keys-handler-service/access-keys.service.ts, libs/ngx-mime/src/lib/viewer/viewer-header/viewer-header.component.html, libs/ngx-mime/src/lib/viewer/viewer-header/viewer-header.component.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: https://github.com/NationalLibraryOfNorway/ngx-mime/issues/265
When toggling fullscreen using the hotkeys focus is set on the mime-viewer container.
Merged enter/exit fullscreen button to not loose focus when toggled via toolbar
```
[ ] Yes
[X] No
```
=> fix: shortcut keys is not working when toggling fullscreen

apps/integration-e2e/pages/viewer.po.ts, package.json
```
[X] Bugfix
[ ] Feature
```
When running e2e tests this error occurs:
UnhandledPromiseRejectionWarning: StaleElementReferenceError: stale element reference: element is not attached to the page document
Handles Promise
```
[ ] Yes
[X] No
```
=> test(e2e): fix stale reference error in e2e test

libs/ngx-mime/src/lib/viewer/viewer-header/viewer-header.component.html
```
[x] Bugfix
[ ] Feature
```
When viewing items with long labels the header buttons overlap each other or overflow on Internet Explorer
Buttons do not overflow or overlap
```
[ ] Yes
[x] No
```
=> fix: avoid buttons overflowing on IE

libs/ngx-mime/src/lib/core/mime-dom-helper.ts
```
[x] Bugfix
[ ] Feature
```
If I open a manifest with an attribution, and then navigation to a view without a viewer. Then the viewer throws an error message.
```
ERROR TypeError: Cannot read property 'focus' of null
at e.setFocusOnViewer (11-es2015.add30e383e71a89a3687.js:1)
```
The viewer checks if there is an viewer to set focus on. 
```
[ ] Yes
[X] No
```
=> fix: cannot read property 'focus' of null

libs/ngx-mime/src/lib/core/viewer-service/iiif-tile-source-strategy.spec.ts, libs/ngx-mime/src/lib/core/viewer-service/iiif-tile-source-strategy.ts
This is a workaround for https://github.com/openseadragon/openseadragon/issues/1722
```
[X] Bugfix
[ ] Feature
```
There is overlap between tiles
Issue Number: #313 
Ther is no overlap btween tiles
```
[ ] Yes
[X] No
```
=> fix: setting default tileOverlap to 0.1

apps/integration-e2e/protractor.conf.js
```
[ ] Bugfix
[ ] Feature
[x] Build related changes
[x] CI related changes
```
E2E test fails on chrome with `UnsupportedOperationError: unknown command: Cannot call non W3C standard command while in W3C mode`
E2E tests pass
```
[ ] Yes
[x] No
```
=> fix: disable w3c mode

libs/ngx-mime/src/lib/core/viewer-service/viewer.service.ts
```
[x] Bugfix
[ ] Feature
```
When scrolling the current canvas group is only calculated every 500ms which can lead to toggling mode on the wrong canvas on click.
The current canvas group is recalculated when the user clicks to switch mode.
```
[ ] Yes
[x] No
```
=> fix: recalculate current canvas group on click outside a canvas group

libs/ngx-mime/src/lib/core/viewer-service/viewer.service.spec.ts, libs/ngx-mime/src/lib/core/viewer-service/viewer.service.ts
```
[x] Bugfix
[ ] Feature
```
Not all OpenSeadragon resources are freed when calling ViewerService.destroy()
All OpenSeadragon resources are freed when calling ViewerService.destroy()
```
[ ] Yes
[x] No
```
=> Fix: free all OpenSeadragon resources on destroy

angular.json, libs/ngx-mime/ng-package.prod.json
```
[ ] Bugfix
[ ] Feature
```
building library gives warning:
```WARNING: No name was provided for external module 'xml2js' in output.globals – guessing 'xml2js'```
and
```alto.service.ts depends on 'xml2js'. CommonJS or AMD dependencies can cause optimization bailouts```
ng-packagr no longer needs to guess and xml2js added to allowedCommonJsDependencies
```
[ ] Yes
[X] No
```
=> build: remove xml2js build warnings

angular.json
```
[] Bugfix
[ ] Feature
```
Getting error “extractCss is deprecated” comes because it has default value as true now. extractCss can be safely removed from angular.json 
removed "extractCss"
```
[ ] Yes
[X] No
```
=> fix:  extractCss is deprecated

libs/ngx-mime/src/lib/viewer/viewer.component.ts
Fixes #349
```
[X] Bugfix
[ ] Feature
```
Issue Number: #349 
Recognized text content is opened when clicking the access key 't' when the attribution dialog is open. It was missing  markForCheck when using access key 't'
```
[ ] Yes
[X] No
```
=> fix: recognized text content is not opened

libs/ngx-mime/src/lib/core/alto-service/alto.service.ts, libs/ngx-mime/src/lib/core/builders/alto/alto.builder.spec.ts, libs/ngx-mime/src/lib/core/builders/alto/print-space.builder.ts, libs/ngx-mime/src/lib/test/testAltos.ts
```
[X] Bugfix
[ ] Feature
```
Issue Number: https://github.com/NationalLibraryOfNorway/ngx-mime/issues/351
Recognized text will now be shown for alto files containing nested ComposedBlocks
```
[ ] Yes
[X] No
```
=> fix: Traversing nested ComposeBlocks to get all TextBlocks

libs/ngx-mime/src/lib/viewer/recognized-text-content/recognized-text-content.component.scss
```
[X] Bugfix
[ ] Feature
```
Opening recognized text with large amount of text makes the container grow outside the viewport and generates double scrollbar
Issue Number: https://github.com/NationalLibraryOfNorway/ngx-mime/issues/355
Recognized text container does not stretch outside viewport
```
[ ] Yes
[X] No
```
=> fix: double scrollbar for recognized-text

libs/ngx-mime/src/lib/core/viewer-service/canvas-group-mask.ts, libs/ngx-mime/src/lib/core/viewer-service/viewer.service.ts
```
[x] Bugfix
[ ] Feature
```
Each time the user rotates the object all subscriptions in ViewerService and CanvasGroupMask are re-added, which leads to new page masks being added for each rotation.
The subscription handling in ViewerService and  CanvasGroupMask now unsubscribes before adding.
```
[ ] Yes
[x] No
```
=> fix: re-initialize subscriptions before adding

libs/ngx-mime/src/lib/core/viewer-service/viewer.service.ts, libs/ngx-mime/src/lib/viewer/viewer.component.html, libs/ngx-mime/src/lib/viewer/viewer.component.ts
…drawer overlaying images
```
[X] Bugfix
[ ] Feature
```
Issue Number: https://github.com/NationalLibraryOfNorway/ngx-mime/issues/359
When the drawer for recognized text is fully opened/closed it will go to home zoom
```
[ ] Yes
[X] No
```
=> fix: recognized text drawer hiding parts of image

libs/ngx-mime/src/lib/core/builders/search-result.builder.spec.ts, libs/ngx-mime/src/lib/core/builders/search-result.builder.ts, libs/ngx-mime/src/lib/core/canvas-group-position/calculate-canvas-group-position-factory.ts, libs/ngx-mime/src/lib/core/canvas-group-position/calculate-canvas-group-position-strategy.ts, libs/ngx-mime/src/lib/core/canvas-group-position/calculate-canvas-group-position-utils.spec.ts, libs/ngx-mime/src/lib/core/canvas-group-position/calculate-canvas-group-position-utils.ts, libs/ngx-mime/src/lib/core/canvas-group-position/one-page-calculate-page-position-strategy.ts, libs/ngx-mime/src/lib/core/canvas-group-position/two-page-calculate-page-position-strategy.ts, libs/ngx-mime/src/lib/core/iiif-content-search-service/iiif-content-search.service.spec.ts, libs/ngx-mime/src/lib/core/iiif-content-search-service/iiif-content-search.service.ts, libs/ngx-mime/src/lib/core/mime-viewer-config.ts, libs/ngx-mime/src/lib/core/utils.ts, libs/ngx-mime/src/lib/core/viewer-service/viewer.service.ts, libs/ngx-mime/src/lib/test/iiif-content-search-service-stub.ts
```
[ ] Bugfix
[x] Feature
```
Utils.getScaleFactor() defaults to 400 if physicalScale is not provided.
By setting ignorePhysicalScale in the config, Utils.getScaleFactor() defaults to 1 (i.e. no scaling).
```
[ ] Yes
[x] No
```
=> feat: ignorePhysicalScale toggle in MimeViewerConfig

libs/ngx-mime/src/lib/content-search-dialog/content-search-dialog.component.scss
```
[X] Bugfix
[ ] Feature
```
When searching for text hits on tablet/mobile it doesn't fill the height of the dialog
Issue Number: #375
The full height of the dialog is now scrollable
```
[ ] Yes
[X] No
```
=> fix: search dialog not filling height of dialog with scrollable content

package.json, yarn.lock
Fixes #378
```
[ ] Bugfix
[X] Feature
```
Issue Number: #378 
Openseadragon is updated from v2.4 to v3
```
[ ] Yes
[X] No
```
=> feat: update openseadragon to v3

libs/ngx-mime/src/lib/core/iiif-content-search-service/iiif-content-search.service.spec.ts, libs/ngx-mime/src/lib/core/iiif-content-search-service/iiif-content-search.service.ts, libs/ngx-mime/src/testing/index.ts, libs/ngx-mime/src/testing/test-manifests.ts
```
[X] Bugfix
[ ] Feature
[X] Code style update (formatting, local variables)
```
NGX-Mime does not reset current q on destroy 
q is reset to an empty string when IiifContentSearchService is destroyed
```
[ ] Yes
[X] No
```
=> fix: cleanup on destroy

libs/ngx-mime/src/lib/attribution-dialog/attribution-dialog.service.ts, libs/ngx-mime/src/lib/canvas-group-dialog/canvas-group-dialog.service.ts, libs/ngx-mime/src/lib/content-search-dialog/content-search-dialog.service.ts, libs/ngx-mime/src/lib/contents-dialog/contents-dialog.service.ts, libs/ngx-mime/src/lib/help-dialog/help-dialog.service.ts, libs/ngx-mime/src/lib/viewer/viewer.component.ts
```
[x] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
ng-mime doesn't always tear down all dialog services and calls user provided emitter outside ngZone
Dialog services always close and unsubscribe before loading a new manifest.
Dialog services use getState() to determine state instead of callbacks
viewerModeChanged emitter is run in ngZone
```
[ ] Yes
[ ] No
```
=> fix: various bugs with dialogs and change detection

libs/ngx-mime/src/lib/viewer/viewer.component.scss, libs/ngx-mime/src/lib/viewer/viewer.component.ts
```
[x] Bugfix
[ ] Feature
```
Highlighting of search hits are fully opaque in Firefox and Safari
Highlighting looks as intended in Firefox and Safari
```
[ ] Yes
[x] No
```
=> fix: make highlighting compatible with firefox & safari

libs/ngx-mime/src/lib/view-dialog/view-dialog.component.html
Fixes #429
```
[X] Bugfix
[ ] Feature
```
Tooltips are blocking click events in View menu
Issue Number: #429 
Removed tooltips since there is labels describing the button
```
[ ] Yes
[X] No
```
=> fix: removed unnecessary labels

libs/ngx-mime/src/lib/contents-dialog/contents-dialog.component.ts
```
[X] Bugfix
[ ] Feature
```
If content dialog stretches longer than viewport it doesn't resize if it's an object without toc, until a CD is triggered by hovering the close button
contents dialog now correctly resizes on objects without toc
```
[ ] Yes
[X] No
```
=> fix: contents-dialog should now resize on objects without toc

libs/ngx-mime/src/lib/core/builders/iiif/search-result.builder.spec.ts, libs/ngx-mime/src/lib/core/builders/iiif/search-result.builder.ts, libs/ngx-mime/src/lib/core/highlight-service/highlight.service.spec.ts, libs/ngx-mime/src/lib/core/models/highlight-rect.ts, libs/ngx-mime/src/lib/core/models/hit.ts, libs/ngx-mime/src/lib/core/viewer-service/viewer.service.ts, libs/ngx-mime/src/lib/test/testManifest.ts, libs/ngx-mime/src/lib/test/testSearchResult.ts, libs/ngx-mime/src/lib/viewer/recognized-text-content/recognized-text-content.component.spec.ts
```
[x] Bugfix
[ ] Feature
```
If you have searchhits going over two pages it doesn't correctly highglight on both pages and just draw both rectangles on the last canvas
Now it correctly draws the rectangles on both canvases
```
[ ] Yes
[x] No
```
=> fix: handle search hits/highlighting over two pages

libs/ngx-mime/src/lib/core/navigation/content-search-navigation-service/content-search-navigation.service.spec.ts, libs/ngx-mime/src/lib/core/navigation/content-search-navigation-service/content-search-navigation.service.ts
- Calling update function when searchresult is changed to update currentHit correctly.
- Fixed a few checks for undefined values
- Added test
```
[x] Bugfix
[ ] Feature
```
When performing a new content search, the current hit in content search navigator does not update according to new searchresult. In some cases you can end up with the navigator displaying "6 of 3 hits", and navigation buttons not working.
currentHit is now reset when searchresult …
=> fix: update currentHit when searchResult is updated

libs/ngx-mime/src/lib/viewer/viewer-footer/content-search-navigator/content-search-navigator.component.ts
```
[X] Bugfix
[ ] Feature
```
Hit status is not updated when a new content search is executed
isFirstHit and isLastHit in ContentSearchNavigatorComponent is updated when serachResult input is changed
```
[ ] Yes
[X] No
```
=> fix: update hit status when searchResult changes

.circleci/config.yml, libs/ngx-mime/src/lib/core/mime-resize-service/mime-resize.service.ts
```
[X] Bugfix
[ ] Feature
```
ResizeObserver is not supported on some old devices (ref: https://caniuse.com/resizeobserver). 
Viewer throws Error `Can't find variable: ResizeObserver`
Resizing will be ignored on devices that do not support ResizeObserver
```
[ ] Yes
[X] No
```
=> fix: handle ResizeObserver not supported

apps/integration-e2e/src/pages/viewer.po.ts, apps/integration-e2e/src/step-definitions/zoom.steps.ts, libs/ngx-mime/ngx-mime.theme.scss, libs/ngx-mime/src/lib/core/intl/viewer-intl.lt.ts, libs/ngx-mime/src/lib/core/intl/viewer-intl.no_nb.ts, libs/ngx-mime/src/lib/core/intl/viewer-intl.ts, libs/ngx-mime/src/lib/shared/animations.ts, libs/ngx-mime/src/lib/viewer/osd-toolbar/animations.ts, libs/ngx-mime/src/lib/viewer/osd-toolbar/osd-toolbar.component.html, libs/ngx-mime/src/lib/viewer/osd-toolbar/osd-toolbar.component.scss, libs/ngx-mime/src/lib/viewer/osd-toolbar/osd-toolbar.component.spec.ts, libs/ngx-mime/src/lib/viewer/osd-toolbar/osd-toolbar.component.theme.scss, libs/ngx-mime/src/lib/viewer/osd-toolbar/osd-toolbar.component.ts, libs/ngx-mime/src/lib/viewer/viewer.component.html, libs/ngx-mime/src/lib/viewer/viewer.component.spec.ts, libs/ngx-mime/src/lib/viewer/viewer.component.ts
```
[ ] Bugfix
[x] Feature
```
The OSD toolbar was in some cases blocking or disturbing the readability of text in objects, especially when zoomed in or when using browser zoom.
The OSD toolbar is replaced with a FAB button and the control buttons are not initially shown. This makes the OSD toolbar cover a much less area than before.
The OSD control buttons can be toggled on and off with this new FAB button.
```
[ ] Yes
[x] No
```
The OSD toolbar also …
=> feat: new layout and behavior for OSD toolbar

.circleci/config.yml
```
[ ] Bugfix
[ ] Feature
```
Build fails with error message: 
error @angular/animations@18.2.9: The engine "node" is incompatible with this module. Expected version "^18.19.1 || ^20.11.1 || >=22.0.0". Got "20.11.0"
Build image is updated to use node 22.0.0
```
[ ] Yes
[X] No
```
=> ci(circleci): update Node.js image to 22.0.0
